# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3419ac04777186d1dd627560cc2f89589742a77985ea901368aecded9ca6c8df79869ed4a350ab96779cfec26f72abef20aaf84bc622fd7072c13ee23d0900dd

test:
  secret_key_base: 2c562de99bef192fa6aa15d3e7d57c59e5c3111d64c82a8f706561fd89a0fc72af4edfc0a347ef58af387f8bc422a7b5e5d4d81d6ea8c4d8af4e9d2d7c37f952

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
